### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by culturetogo** [nishad/omeka-s-wikidata#2]
Hi Nishhad, 

I've just tried to install the wikidata module on a brand new Omeka S installation (3.0.1) and got the error message: Error: Wikidata requires Omeka S ^1.0.0 || ^2.0.0 Does that mean it will not run with version 3.x? Any plans to make it happen? Would be great to have a Wikidata connector for use in Omeka ...
Best Michael

**Comment by lklic** [comment]
we would also like this to be updated to support version 3, any plans to update it?

Wikidata is a critical dataset to be able to to query!


Thanks!

**Comment by nishad** [comment]
Thanks for reporting the requirement. With the release [v1.3.0](https://github.com/nishad/omeka-s-wikidata/releases/tag/v1.3.0), Wikidata module supports Omeka-S v3
