### ISSUE TITLE
omeka s version 3 support breaks functionality of ValueSuggest module

### ISSUE THREAD

**Issue by lklic** [nishad/omeka-s-wikidata#3]
adding this module breaks the functionality of the ValueSuggest module:https://github.com/omeka-s-modules/ValueSuggest

This is the case both if you have one field that uses multiple vocabs as well as a field that uses only one vocab from ValueSuggest.

If you deactivate the WikiData module the ValueSuggest module works again.

Can you please look into fixing this?

Thanks!

**Comment by Daniel-KM** [comment]
Fixed in #5.
