### ISSUE TITLE
Error (update needed)

### ISSUE THREAD

**Issue by Broekhuis** [nishad/omeka-s-wikidata#8]
Hi, I'm using Omeka S 4.01 and I'm getting this error :

Error: Wikidata requires Omeka S ^3.0.0

Will there be an update for v4+ ?

**Comment by xulei-shl** [comment]
+1

**Comment by juanfuc** [comment]
You can edit the module.ini file changing this line: omeka_version_constraint = "^3.0.0", For this one:  omeka_version_constraint = "^3.0.0 || ^4.0.0"

**Comment by nishad** [comment]
Hi @juanfuc thank you. Do you mind sending a PR, I will merge that.

**Comment by juanfuc** [comment]
Hi @nishad. Thanks! I’ve submitted the PR. Let me know if anything else is
needed.

Best,

**Comment by nishad** [comment]
Thank you @juanfuc. I have merged this PR and released [v1.4.1](https://github.com/nishad/omeka-s-wikidata/releases/tag/v1.4.1). The official module page ([https://omeka.org/s/modules/Wikidata/](https://omeka.org/s/modules/Wikidata/)) will be automatically updated in a day.
